TILE_EMPTY      = 0
TILE_WALL       = 1

STRUCT_CROSS    = 0
STRUCT_VLINE    = 1
STRUCT_HLINE    = 2
STRUCT_ELBOW_1  = 3
STRUCT_ELBOW_2  = 4
STRUCT_ELBOW_3  = 5
STRUCT_ELBOW_4  = 6
STRUCT_T_1      = 7
STRUCT_T_2      = 8
STRUCT_T_3      = 9
STRUCT_T_4      = 10

STRUCT_SIDE   = 3
STRUCT_NUMBER   = 11

STRUCT = [None] * STRUCT_NUMBER

STRUCT[STRUCT_CROSS] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_VLINE] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_HLINE] = [
    TILE_WALL, TILE_WALL, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_WALL, TILE_WALL
]

STRUCT[STRUCT_ELBOW_1] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_WALL, TILE_WALL
]

STRUCT[STRUCT_ELBOW_2] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_WALL, TILE_WALL
]

STRUCT[STRUCT_ELBOW_3] = [
    TILE_WALL, TILE_WALL, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_ELBOW_4] = [
    TILE_WALL, TILE_WALL, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_T_1] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_T_2] = [
    TILE_WALL, TILE_WALL, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]

STRUCT[STRUCT_T_3] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_WALL, TILE_WALL
]

STRUCT[STRUCT_T_4] = [
    TILE_WALL, TILE_EMPTY, TILE_WALL,
    TILE_WALL, TILE_EMPTY, TILE_EMPTY,
    TILE_WALL, TILE_EMPTY, TILE_WALL
]